In [1]:
import numpy as np

In [3]:
arr = np.array([1,2,3,4,5,6,7,8,9])
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
type(arr)

numpy.ndarray

In [6]:
array = np.array([[1,2,3],[4,5,6],[7,8,9]])
array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
np.array(np.arange(1,10)).reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
arr.ndim, array.ndim

(1, 2)

In [13]:
arr.dtype, array.dtype

(dtype('int64'), dtype('int64'))

In [14]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [20]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [21]:
np.full((3,4),5)

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [30]:
np.linspace(1,100,20).reshape(4,5)

array([[  1.        ,   6.21052632,  11.42105263,  16.63157895,
         21.84210526],
       [ 27.05263158,  32.26315789,  37.47368421,  42.68421053,
         47.89473684],
       [ 53.10526316,  58.31578947,  63.52631579,  68.73684211,
         73.94736842],
       [ 79.15789474,  84.36842105,  89.57894737,  94.78947368,
        100.        ]])

In [35]:
random = np.random.rand(3,5)
random

array([[0.97753043, 0.25317104, 0.66503136, 0.26828002, 0.02281258],
       [0.93567095, 0.85604943, 0.87427429, 0.15888577, 0.5243938 ],
       [0.04409123, 0.91697538, 0.81571914, 0.03404066, 0.142252  ]])

In [41]:
np.random.seed(seed=10)
df=np.random.randint(1,10,(3,5))


In [45]:
df[1:,2:]

array([[9, 7, 5],
       [5, 7, 9]], dtype=int32)

In [46]:
np.unique(df)

array([1, 2, 4, 5, 7, 9], dtype=int32)

#   Dot product

In [81]:
np.random.seed(seed=10)
mat1= np.random.randint(1,30,(3,5))
mat2= np.random.randint(1,30,(5,3))

In [56]:
mat1

array([[11, 14, 26, 12,  2],
       [19, 14,  9, 26, 10],
       [ 6,  1, 19, 24,  4]], dtype=int32)

In [57]:
mat2

array([[17, 21, 19, 17, 15],
       [20, 16, 20, 18, 19],
       [22, 26, 15, 17, 11]], dtype=int32)

In [58]:
mat1*mat2

array([[187, 294, 494, 204,  30],
       [380, 224, 180, 468, 190],
       [132,  26, 285, 408,  44]], dtype=int32)

In [60]:
#Dot product
np.dot(mat1, mat2)

array([[ 658,  597, 1122],
       [1386, 1022, 1730],
       [1180,  384, 1294]], dtype=int32)

In [61]:
mat=np.array([[2,7,1],
              [9,4,16],
              [11,14,18],
              [13,13,16],
              [15,18,9]])

In [65]:
Price=np.array([[10],[8],[12]])
Price

array([[10],
       [ 8],
       [12]])

In [67]:
total_sales=np.dot(mat,Price)

In [68]:
total_sales

array([[ 88],
       [314],
       [438],
       [426],
       [402]])

In [69]:
import pandas as pd

In [76]:
Sales = pd.DataFrame(mat,index=['Mon','Tues','Wed','Thurs','Fri'], columns=['Almond butter','Peanut butter','Cashew butter'])
Sales['total_sales($)']= total_sales
Sales

,Almond butter,Peanut butter,Cashew butter,total_sales($)
Mon,2,7,1,88
Tues,9,4,16,314
Wed,11,14,18,438
Thurs,13,13,16,426
Fri,15,18,9,402


In [82]:
mat2

array([[ 9, 23,  5],
       [20, 17,  5],
       [16, 12, 23],
       [25, 12, 27],
       [ 2,  9,  5]], dtype=int32)

In [85]:
mat2.sort(axis=1)
mat2

array([[ 5,  9, 23],
       [ 5, 17, 20],
       [12, 16, 23],
       [12, 25, 27],
       [ 2,  5,  9]], dtype=int32)

# practial Example

In [93]:
from matplotlib.image import imread
lion = imread("lion.jpg")
lion

array([[[154, 167, 175],
        [154, 167, 175],
        [154, 167, 175],
        ...,
        [162, 173, 177],
        [161, 172, 176],
        [161, 172, 176]],

       [[154, 167, 175],
        [154, 167, 175],
        [154, 167, 175],
        ...,
        [162, 173, 177],
        [162, 173, 177],
        [161, 172, 176]],

       [[155, 168, 174],
        [155, 168, 174],
        [155, 168, 174],
        ...,
        [162, 173, 177],
        [162, 173, 177],
        [162, 173, 177]],

       ...,

       [[ 22,  14,  11],
        [ 29,  21,  18],
        [ 28,  20,  17],
        ...,
        [216, 162, 116],
        [217, 163, 117],
        [219, 165, 119]],

       [[ 25,  17,  14],
        [ 30,  22,  19],
        [ 29,  21,  18],
        ...,
        [207, 154, 110],
        [207, 154, 110],
        [209, 156, 112]],

       [[ 27,  19,  16],
        [ 32,  24,  21],
        [ 29,  21,  18],
        ...,
        [200, 147, 103],
        [199, 146, 102],
        [200, 147, 103]]

In [94]:
lion.size

479568

In [95]:
lion.shape

(412, 388, 3)

In [96]:
lion.ndim

3

In [98]:
rab = imread("1.jpg")
rab

array([[[ 92, 113, 142],
        [ 97, 118, 147],
        [102, 123, 152],
        ...,
        [ 99, 136, 178],
        [ 99, 136, 178],
        [ 99, 136, 178]],

       [[ 92, 113, 142],
        [ 96, 117, 146],
        [ 98, 119, 148],
        ...,
        [103, 140, 182],
        [106, 143, 185],
        [109, 146, 188]],

       [[ 96, 115, 145],
        [ 96, 115, 145],
        [ 97, 116, 146],
        ...,
        [112, 150, 189],
        [118, 156, 195],
        [123, 161, 200]],

       ...,

       [[  1,  93, 140],
        [  1,  93, 140],
        [  1,  93, 140],
        ...,
        [  3,  98, 144],
        [  3,  98, 144],
        [  3,  98, 144]],

       [[  2,  93, 140],
        [  2,  93, 140],
        [  2,  93, 140],
        ...,
        [  3,  98, 144],
        [  3,  98, 144],
        [  3,  98, 144]],

       [[  2,  93, 140],
        [  2,  93, 140],
        [  2,  93, 140],
        ...,
        [  3,  98, 144],
        [  3,  98, 144],
        [  3,  98, 144]]